using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace TabForge.Diagnostics;

/// <summary>
/// Builds <c>docs/feature-map/files.md</c>: every C# source file under <c>src/</c> grouped by folder, each with a one-line purpose
/// taken from its <c>Owns:</c> header or else the first sentence of its first summary comment (blank when it has neither).
/// Owns: the file walk, the purpose extraction and the generated text. Does not own: writing it (FeatureMapGenerator.Run) or the sync check (SelfTestFeatureMap).
/// Tests: TestFileIndexInSync.
/// </summary>
internal static class FileIndexGenerator
{
    public const string GeneratedRelativePath = "docs/feature-map/files.md";
    private const int MaxPurpose = 110;
    private static readonly Regex Owns = new(@"Owns:\s*(?<t>.+)", RegexOptions.Compiled);
    private static readonly Regex Tag = new(@"<[^>]+>", RegexOptions.Compiled);

    /// <summary>Source files (repository-relative, forward slashes) in ordinal order, skipping build output.</summary>
    internal static List<string> SourceFiles(string root) =>
        Directory.EnumerateFiles(Path.Combine(root, "src"), "*.cs", SearchOption.AllDirectories)
            .Select(p => Path.GetRelativePath(root, p).Replace('\\', '/'))
            .Where(p => !p.Contains("/obj/") && !p.Contains("/bin/"))
            .OrderBy(p => p, StringComparer.Ordinal).ToList();

    /// <summary>The purpose line of one source file's text.</summary>
    internal static string Purpose(string text)
    {
        var head = text.Split('\n').Take(60).Select(l => l.Trim().TrimStart('/').Trim()).ToList();
        string? raw = null;
        var owns = head.Select(l => Owns.Match(l)).FirstOrDefault(m => m.Success);
        if (owns is not null) raw = owns.Groups["t"].Value;
        else
        {
            var start = head.FindIndex(l => l.StartsWith("<summary>", StringComparison.Ordinal));
            if (start >= 0)
            {
                var parts = new List<string>();
                for (var i = start; i < head.Count; i++)
                {
                    parts.Add(head[i]);
                    if (head[i].Contains("</summary>", StringComparison.Ordinal)) break;
                }
                raw = string.Join(" ", parts);
            }
        }
        if (raw is null) return "";
        var s = Regex.Replace(Tag.Replace(raw, ""), @"\s+", " ").Trim();
        var cut = s.IndexOf(" Does not own", StringComparison.Ordinal);
        if (cut > 0) s = s[..cut];
        var dot = s.IndexOf(". ", StringComparison.Ordinal);
        if (dot > 0) s = s[..dot];
        s = s.TrimEnd('.', ' ', ';').Replace("|", "/");
        return s.Length > MaxPurpose ? s[..(MaxPurpose - 3)].TrimEnd() + "..." : s;
    }

    /// <summary>The generated page: one table per source folder, file name and purpose.</summary>
    internal static string Render(string root)
    {
        var sb = new StringBuilder();
        sb.Append("# File index\n\nGenerated by `TabForge.exe --feature-map` from the source. Do not edit by hand. Index: [Feature map](../FEATURE_MAP.md). ");
        sb.Append("Purpose is the file's `Owns:` header or first summary sentence; blank means the file has neither.\n");
        var missing = new List<string>();
        foreach (var folder in SourceFiles(root).GroupBy(p => p[..p.LastIndexOf('/')]))
        {
            sb.Append($"\n## {folder.Key}\n\n| File | Purpose |\n| --- | --- |\n");
            foreach (var path in folder)
            {
                var purpose = Purpose(File.ReadAllText(Path.Combine(root, path)));
                if (purpose.Length == 0) missing.Add(path);
                sb.Append($"| {path[(folder.Key.Length + 1)..]} | {purpose} |\n");
            }
        }
        if (missing.Count > 0)
        {
            sb.Append("\n## Missing purpose\n\nFiles with neither an `Owns:` header nor a summary sentence. Each needs an `// Owns:` header.\n\n");
            foreach (var missingPath in missing) sb.Append($"- {missingPath}\n");
        }
        return sb.ToString().TrimEnd('\n').Replace("\n", "\r\n") + "\r\n";
    }
}
