using System.Windows;
using System.Windows.Controls;
using TabForge.Views;
using static TabForge.Views.MenuRow;

namespace TabForge;

// Owns: the table of plain main-menu commands (header, command id, click handler) and the call that inserts them into the menu
//   skeleton of MainWindow.xaml once at startup.
// Does not own: the skeleton and the complex items (checkable, named, dynamic) in MainWindow.xaml, the handlers, or gesture text.
// Tests: TestMainMenuTable, TestMainMenuTreeGolden.
public partial class MainWindow
{
    private void BuildMainMenuFromTable() => MenuTable.Build(MainMenu, MainMenuGroups());

    /// <summary>The plain rows: this table plus the rows the feature modules contribute (Services/Features).</summary>
    internal MenuGroup[] MainMenuGroups() => MenuTable.AddFeatureRows(new MenuGroup[]
    {
        new("_Help", null,
            Item("Tutorial…", Tutorial_Click, "Help.Tutorial"),
            Item("Detailed guide…", TutorialDetailed_Click, "Help.TutorialDetailed"),
            Item("Keyboard shortcuts…", Shortcuts_Click, "App.Shortcuts"),
            Item("Check for updates…", CheckForUpdates_Click, "Help.CheckForUpdates"),
            Item("About", About_Click)),
        new("_Options", null,
            Item("Stylesheet…", Stylesheet_Click),
            Item("Preferences…", Prefs_Click, "App.Preferences")),
        new("_Sound", null,
            Item("Play / pause", Play_Click, "Transport.PlayPause"),
            Item("Play from beginning", PlayFromStart_Click, "Transport.PlayFromStart"),
            Item("First bar", FirstBar_Click, "Bar.First"),
            Item("Last bar", LastBar_Click, "Bar.Last"),
            Sep,
            Item("Empty bar", EmptyBar_Click),
            Item("MIDI / Audio setup", ShowAudioTab_Click),
            Item("Test selected track output", TestMidi_Click)),
        new("_Sections", null,
            Item("Add section…", AddMarker_Click, "Section.Add"),
            Item("Go to…", GoTo_Click, "Bar.GoTo"),
            Item("Previous section", PrevSection_Click, "Section.Previous"),
            Item("Next section", NextSection_Click, "Section.Next")),
        new("_Track", null,
            Item("Add _Guitar", AddGuitar_Click, "Track.Add"),
            Item("Add _Bass", AddBass_Click),
            Item("Add _Drums", AddDrums_Click),
            Item("Add _Keys", AddKeys_Click),
            Sep,
            Item("_Delete track", DeleteTrack_Click, "Track.Delete"),
            Item("Move _up", MoveTrackUp_Click, "Track.MoveUp"),
            Item("Move _down", MoveTrackDown_Click, "Track.MoveDown"),
            Sep,
            Item("_Properties…", TrackProps_Click, "Track.Properties")),
        new("_Edit", null,
            Item("_Undo", Undo_Click, "Edit.Undo"),
            Item("_Redo", Redo_Click, "Edit.Redo"),
            Sep,
            Item("_Copy", Copy_Click, "Edit.Copy"),
            Item("Cu_t", Cut_Click, "Edit.Cut"),
            Item("_Paste", Paste_Click, "Edit.Paste"),
            Item("Paste _special…", PasteSpecial_Click, "Edit.PasteSpecial"),
            Sep,
            Item("_Insert beat", InsertBeat_Click, "Edit.InsertBeat"),
            Item("_Delete beats", DeleteBeats_Click, "Edit.DeleteBeats"),
            Item("_Copy last beat", CopyBeats_Click, "Note.RepeatBeat")),
        new("_Bar", null,
            Item("Insert _bar", InsertBar_Click, "Bar.Insert"),
            Item("_Delete bar", DeleteBar_Click, "Bar.Delete"),
            Item("Duplicate bar", DuplicateBar_Click),
            Item("Repeat selection as bars", RepeatSelection_Click, "Edit.RepeatSelection"),
            Sep,
            Item("_Time signature…", TimeSig_Click, "Bar.TimeSignature"),
            Item("_Key signature…", KeySig_Click, "Bar.KeySignature"),
            Item("_Clef", Clef_Click, "Bar.Clef"),
            Item("Triplet _feel", TripletFeel_Click),
            Sep,
            Item("Repeat _open", RepeatOpen_Click, "Bar.RepeatOpen"),
            Item("Repeat _close…", RepeatClose_Click, "Bar.RepeatClose"),
            Item("_Directions / ending…", Directions_Click, "Bar.Directions"),
            Item("_Double bar", DoubleBar_Click),
            Item("Repeat one _bar", Simile1_Click),
            Item("Repeat two b_ars", Simile2_Click),
            Sep,
            Item("_Section…", Section_Click, "Section.Edit")),
        new("_Tools", null,
            Item("Check bar duration", CheckBars_Click, "Bar.Check"),
            Item("Transpose…", Transpose_Click, "Tools.Transpose"),
            Item("Scale finder…", ScaleFinder_Click, "Tools.ScaleFinder"),
            Item("Chord finder…", ChordFinder_Click, "Tools.ChordFinder"),
            Item("Song stats…", SongStats_Click, "Tools.SongStats"),
            Item("Tuner…", Tuner_Click, "Tools.Tuner"),
            Sep),
        new("_View", null,
            Item("Tablature + standard", NotationBoth_Click),
            Item("Tablature only", NotationTab_Click),
            Item("Standard notation only", NotationStaff_Click),
            Sep,
            Item("Dark score page", ThemeDark_Click),
            Item("Light score page", ThemeLight_Click),
            Sep),
        new("_View", "PlayingBarMenu",
            Item("Mixer / VST", ShowMixer_Click, "View.Mixer"),
            Sep),
        new("_View", "DockPanelsMenu",
            Item("Reset all panels to default positions", ResetDockWorkspace_Click),
            Sep,
            Item("Zoom 75%", Zoom75_Click),
            Item("Zoom 100%", Zoom100_Click),
            Item("Zoom 150%", Zoom150_Click),
            Item("Full screen", Fullscreen_Click, "View.Fullscreen")),
        new("_Note", null,
            Item("Whole", Dur1_Click),
            Item("Half", Dur2_Click),
            Item("Quarter", Dur4_Click),
            Item("Eighth", Dur8_Click),
            Item("Sixteenth", Dur16_Click),
            Item("32nd", Dur32_Click),
            Item("64th", Dur64_Click),
            Sep,
            Item("Longer note value", DurLonger_Click, "Note.Longer"),
            Item("Shorter note value", DurShorter_Click, "Note.Shorter"),
            Item("Dotting", Dot_Click, "Note.Dot"),
            Item("Double dotting", DoubleDot_Click, "Note.DoubleDot"),
            Item("Triplet", Triplet_Click, "Note.Triplet"),
            Sep,
            Item("Tie note", Tie_Click, "Note.Tie"),
            Item("Rest", Rest_Click, "Note.Rest"),
            Item("Fermata", Fermata_Click, "Note.Fermata"),
            Item("Accent", Accent_Click, "Note.Accent"),
            Item("Staccato", Staccato_Click, "Note.Staccato"),
            Item("Tenuto", Tenuto_Click, "Note.Tenuto"),
            Sep,
            Item("Shift pitch up (semitone)", PitchUp_Click, "Note.PitchUp"),
            Item("Shift pitch down (semitone)", PitchDown_Click, "Note.PitchDown"),
            Item("Move to higher string", MoveUpString_Click, "Note.MoveStringUp"),
            Item("Move to lower string", MoveDownString_Click, "Note.MoveStringDown")),
        new("_Effects", null,
            Item("Dead note", FxDead_Click, "Note.Dead"),
            Item("Ghost note", FxGhost_Click, "Note.Ghost"),
            Item("Palm mute", PalmMute_Click, "Note.PalmMute"),
            Item("Let ring", LetRing_Click, "Note.LetRing"),
            Item("Hammer / pull", Hopo_Click, "Note.HammerPull"),
            Item("Bend", Bend_Click, "Note.Bend"),
            Item("Bend editor…", EffectEditor_Click, "Note.BendEditor", "Bend"),
            Item("Legato slide", Slide_Click, "Note.Slide"),
            Item("Shift slide", FxShiftSlide_Click),
            Item("Vibrato", Vibrato_Click, "Note.Vibrato"),
            Item("Wide vibrato", FxWideVib_Click),
            Item("Tremolo bar", FxTremBar_Click, "Note.TremoloBar"),
            Item("Tremolo bar editor…", EffectEditor_Click, "Note.TremoloBarEditor", "TremoloBar"),
            Item("Natural harmonic", FxHarm_Click, "Note.Harmonic"),
            Item("Harmonic editor…", EffectEditor_Click, "Note.HarmonicEditor", "Harmonic"),
            Item("Trill editor…", EffectEditor_Click, "Note.TrillEditor", "Trill"),
            Item("Grace note editor…", EffectEditor_Click, "Note.GraceEditor", "Grace"),
            Item("Artificial harmonic", FxArtHarm_Click),
            Item("Tapping", FxTap_Click),
            Item("Slap", FxSlap_Click),
            Item("Pop", FxPop_Click),
            Item("Trill", FxTrill_Click, "Note.Trill"),
            Item("Tremolo picking", FxTremPick_Click),
            Item("Fade in", FxFadeIn_Click, "Note.FadeIn"),
            Item("Fade out", FxFadeOut_Click, "Note.FadeOut"),
            Item("Wah open", FxWahOpen_Click),
            Item("Wah close", FxWahClose_Click),
            Item("Brush down", FxBrushDown_Click),
            Item("Brush up", FxBrushUp_Click),
            Item("Arpeggio down", FxArpDown_Click),
            Item("Arpeggio up", FxArpUp_Click),
            Item("Grace before beat", FxGrace_Click, "Note.Grace"),
            Sep,
            Item("Chord…", Chord_Click, "Note.Chord"),
            Item("Text…", Text_Click, "Note.Text")),
        new("_File", null,
            Item("_New", New_Click, "File.New"),
            Item("New from t_emplate…", ApplyTemplate_Click, "File.NewFromTemplate"),
            Item("New _tab", NewTab_Click, "Tab.New"),
            Item("_Open…", Open_Click, "File.Open"),
            Item("Open in new _tab…", OpenInNewTab_Click, "File.OpenInNewTab"),
            Item("_Save", Save_Click, "File.Save"),
            Item("Save _As…", SaveAs_Click, "File.SaveAs"),
            Item("_Close tab", CloseTab_Click, "Tab.Close"),
            Sep,
            Item("Export _MIDI…", (_, _) => ExportMidi(), "File.ExportMidi"),
            Item("_Render to audio file…", Render_Click, "File.Render"),
            Item("Command pa_lette…", CommandPalette_Click, "App.CommandPalette"),
            Sep,
            Item("Score _information…", ScoreInfo_Click, "Bar.ScoreInfo"),
            Item("Print _preview…", PrintPreview_Click, "File.PrintPreview"),
            Item("_Print…", Print_Click, "File.Print"),
            Sep,
            Item("E_xit", Exit_Click)),
        // <groups>
    }, id => Commands.TryRun(id));   // a lambda: the command table is built at the first hotkey or menu use, not here
}
