# Builds native\tfvst3 (x64 Release, static CRT) and copies tfvst3.dll to src\TabForge.AudioEngine\native\.
# Fetches (and verifies the pin of) the VST3 SDK first, then records native\BUILD_PROVENANCE.md:
# SDK commit, compiler version and the SHA-256 of the produced tfvst3.dll. Package-Release.ps1 checks the
# shipped DLL against that recorded hash.
# -BuildDir puts the CMake build folder elsewhere (CI uses a short path; the SDK has very long file names).
[CmdletBinding()]
param([switch]$Clean, [switch]$NoTest, [string]$BuildDir = '')
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$src = Join-Path $PSScriptRoot 'tfvst3'
$buildDir = if ($BuildDir) { $BuildDir } else { Join-Path $src 'build' }
$sdk = Join-Path $repoRoot 'third_party\vst3sdk'
$destDir = Join-Path $repoRoot 'src\TabForge.AudioEngine\native'
$provenance = Join-Path $PSScriptRoot 'BUILD_PROVENANCE.md'

$cmake = 'C:\Program Files\CMake\bin\cmake.exe'
if (-not (Test-Path $cmake)) { $cmake = 'cmake' }
$git = 'C:\Program Files\Git\cmd\git.exe'
if (-not (Test-Path $git)) { $git = 'git' }

# Always run the fetch script: it fetches when missing and otherwise verifies the SDK is at the pinned commit.
& (Join-Path $PSScriptRoot 'fetch-vst3sdk.ps1')
if ($Clean -and (Test-Path $buildDir)) { Remove-Item -Recurse -Force $buildDir }

# Pick the newest Visual Studio generator that configures.
$testFlag = if ($NoTest) { 'OFF' } else { 'ON' }
$configured = Test-Path (Join-Path $buildDir 'CMakeCache.txt')
$generator = $null
if (-not $configured) {
    foreach ($gen in @('Visual Studio 18 2026', 'Visual Studio 17 2022')) {
        Write-Host "Configuring with '$gen'..."
        & $cmake -S $src -B $buildDir -G $gen -A x64 "-DTFVST3_BUILD_TEST=$testFlag" "-DVST3SDK_DIR=$sdk"
        if ($LASTEXITCODE -eq 0) { $configured = $true; $generator = $gen; break }
        if (Test-Path $buildDir) { Remove-Item -Recurse -Force $buildDir }
    }
    if (-not $configured) { throw 'CMake configure failed for all Visual Studio generators' }
}

& $cmake --build $buildDir --config Release --parallel
if ($LASTEXITCODE -ne 0) { throw "tfvst3 build failed ($LASTEXITCODE)" }

$dll = Join-Path $buildDir 'Release\tfvst3.dll'
if (-not (Test-Path $dll)) { throw "build succeeded but $dll is missing" }
New-Item -ItemType Directory -Force $destDir | Out-Null
Copy-Item $dll (Join-Path $destDir 'tfvst3.dll') -Force
Write-Host "tfvst3.dll -> $destDir"

# ---- provenance -------------------------------------------------------------------------------------
$sdkCommit = (& $git -C $sdk rev-parse HEAD).Trim()
$sdkDescribe = (& $git -C $sdk describe --tags --always 2>$null | Out-String).Trim()
$compilerVersion = 'unknown'
$compilerId = 'unknown'
$cxxInfo = Get-ChildItem -Path (Join-Path $buildDir 'CMakeFiles') -Filter 'CMakeCXXCompiler.cmake' -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
if ($cxxInfo) {
    $text = [IO.File]::ReadAllText($cxxInfo.FullName)
    if ($text -match 'set\(CMAKE_CXX_COMPILER_VERSION "([^"]+)"\)') { $compilerVersion = $Matches[1] }
    if ($text -match 'set\(CMAKE_CXX_COMPILER_ID "([^"]+)"\)') { $compilerId = $Matches[1] }
}
if (-not $generator -and (Test-Path (Join-Path $buildDir 'CMakeCache.txt'))) {
    $cache = [IO.File]::ReadAllText((Join-Path $buildDir 'CMakeCache.txt'))
    if ($cache -match 'CMAKE_GENERATOR:INTERNAL=(.+)') { $generator = $Matches[1].Trim() }
}
$cmakeVersion = ((& $cmake --version | Select-Object -First 1) -replace 'cmake version ', '').Trim()
$dllHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $dll).Hash.ToLowerInvariant()
$sources = @('tfvst3.cpp', 'tfvst3.h', 'CMakeLists.txt') | ForEach-Object {
    $p = Join-Path $src $_
    "- $_ SHA-256: $((Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant())"
}

$lines = @(
    '# tfvst3 build provenance',
    '',
    'Generated by `native/build-tfvst3.ps1`; do not edit by hand. `tools/Package-Release.ps1` verifies the shipped',
    '`tfvst3.dll` against the hash recorded here, and `tools/Write-Sbom.ps1` copies it into `docs/SBOM.md`.',
    '',
    "- Built (UTC): $([DateTime]::UtcNow.ToString('yyyy-MM-dd HH:mm:ss'))",
    "- VST3 SDK commit: $sdkCommit",
    "- VST3 SDK git describe: $sdkDescribe",
    "- Compiler: $compilerId $compilerVersion",
    "- CMake: $cmakeVersion; generator: $generator; platform x64, configuration Release, static CRT",
    "- Tests built: $testFlag",
    '',
    '## Bridge source inputs',
    ''
) + $sources + @(
    '',
    '## Output',
    '',
    "tfvst3.dll SHA-256: $dllHash"
)
# Written as ASCII with CRLF line endings (matches .gitattributes; safe for Windows PowerShell 5.1 readers).
[IO.File]::WriteAllText($provenance, (($lines -join "`r`n") + "`r`n"), [Text.Encoding]::ASCII)
Write-Host "Provenance -> $provenance (tfvst3.dll SHA-256 $dllHash)"
