// Owns: the table of bindable commands (id, category, name, default keys, description), built once in four slices.
// Does not own: lookup, gestures and presets (HotkeyCatalog.cs).
// Tests: TestNewBindableCommands, TestKeyRoutingOrder.
namespace TabForge.Services;

public static partial class HotkeyCatalog
{
    private static List<HotkeyAction> BuildActions()
    {
        var all = new List<HotkeyAction>(300);
        all.AddRange(SliceA());
        all.AddRange(SliceB());
        all.AddRange(SliceC());
        all.AddRange(SliceD());
        Features.FeatureRegistry.AddHotkeys(all);
        return all;
    }

    private static HotkeyAction[] SliceA() => new HotkeyAction[]
    {
        new("File.New", CategoryFile, "New score", "Ctrl+N", "Create a new score in a new tab."),
        new("File.NewFromTemplate", CategoryFile, "New from template", "", "Create a new score from a built-in or saved template (File > New from template)."),
        new("File.Open", CategoryFile, "Open score", "Ctrl+O", "Open a .tforge or .gp file in the current tab."),
        new("File.OpenInNewTab", CategoryFile, "Open score in new tab", "Ctrl+Shift+O", "Open a .tforge or .gp file in a new tab."),
        new("File.Save", CategoryFile, "Save", "Ctrl+S", "Save the active score."),
        new("File.SaveAs", CategoryFile, "Save as", "Ctrl+Shift+S", "Save the active score under a new name."),
        new("File.Print", CategoryFile, "Print", "Ctrl+P", "Print the active score."),
        new("File.PrintPreview", CategoryFile, "Print preview", "Ctrl+Shift+P", "Preview the printed page."),
        new("File.CancelImport", CategoryFile, "Cancel import", "", "Cancel the score import(s) running in the background (same as the status-bar Cancel button)."),
        new("File.ProjectSettings", CategoryFile, "Project settings", "", "Open the project settings: song info, credits, tempo and key (the toolbar's Project settings button)."),
        new("App.CommandPalette", CategoryFile, "Command palette", "Ctrl+Shift+A", "Search every command by name, see its key and run it."),
        new("File.Render", CategoryFile, "Render to audio file", "Ctrl+Alt+R", "Render the song to WAV / MP3 (master mix and / or stems) faster than realtime."),
        new("Tab.New", CategoryFile, "New tab", "Ctrl+T", "Open another score in a new tab."),
        new("Tab.Close", CategoryFile, "Close tab", "Ctrl+W", "Close the active tab."),
        new("Tab.Duplicate", CategoryFile, "Duplicate tab", "Ctrl+Shift+D", "Duplicate the active tab as an unsaved copy."),
        new("App.Preferences", CategoryFile, "Preferences", "F12", "Open this settings window."),
        new("App.Shortcuts", CategoryFile, "Keyboard shortcuts", "F1", "Show the shortcut reference."),

        new("Edit.Undo", CategoryEdit, "Undo", "Ctrl+Z", "Undo the last edit."),
        new("Edit.Redo", CategoryEdit, "Redo", "Ctrl+Y", "Redo the last undone edit."),
        new("Edit.Copy", CategoryEdit, "Copy", "Ctrl+C", "Copy the selected beats or bars, or the beat at the cursor."),
        new("Edit.Cut", CategoryEdit, "Cut", "Ctrl+X", "Cut the selected beats or bars (later beats move up; whole bars are removed, or emptied on one track of several)."),
        new("Edit.Paste", CategoryEdit, "Paste", "Ctrl+V", "Paste at the cursor; asks only what the paste needs."),
        new("Edit.PasteSpecial", CategoryEdit, "Paste special", "Ctrl+Shift+V", "Paste with a repeat count, replace or insert, octave shift, keep string and fret, and bar settings."),
        new("Edit.SelectAll", CategoryEdit, "Select whole track", "Ctrl+A", "Select every bar of the track."),
        new("Edit.InsertBeat", CategoryEdit, "Insert beat", "Insert", "Insert an empty beat at the cursor and push the rest of the bar right (the bar keeps its length)."),
        new("Edit.DeleteBeats", CategoryEdit, "Delete beats (shift left)", "", "Remove the beat at the cursor and pull the rest of the bar left. Remove the beat at the cursor and pull the rest of the bar left. The Delete key clears the notes first, and removes an empty beat the same way."),
        new("Edit.RepeatSelection", CategoryEdit, "Repeat selection", "Ctrl+Shift+R", "Repeat the selected bars."),

        new("Transport.PlayPause", CategoryTransport, "Play / pause", "Space", "Start or pause playback."),
        new("Transport.PlayFromStart", CategoryTransport, "Play from the start", "Shift+Space", "Restart playback from the beginning."),
        new("Playback.SpeedUp", CategoryTransport, "Speed up", "Ctrl+Alt+Up", "Playback speed to the next preset (50, 75, 100, 125, 150, 200 %)."),
        new("Playback.SpeedDown", CategoryTransport, "Slow down", "Ctrl+Alt+Down", "Playback speed to the previous preset (50, 75, 100, 125, 150, 200 %)."),
        new("Playback.SpeedReset", CategoryTransport, "Reset speed to 100 %", "Ctrl+Alt+D0", "Play at the song's own tempo (100 %)."),
        new("Transport.Stop", CategoryTransport, "Stop", "Ctrl+OemPeriod", "Stop playback and return to the edit cursor."),
        new("Transport.Loop", CategoryTransport, "Loop", "F9", "Play the loop range repeatedly."),
        new("Transport.Metronome", CategoryTransport, "Metronome on / off", "", "Turn the metronome click on or off (the same as the transport's Metronome button)."),
        new("Transport.CountIn", CategoryTransport, "Count-in on / off", "", "Turn the count-in before playback on or off (the same as the transport's Count-in button)."),

        new("Bar.Insert", CategoryBar, "Insert bar", "Ctrl+Insert", "Insert an empty bar before the cursor."),
    };

    private static HotkeyAction[] SliceB() => new HotkeyAction[]
    {
        new("Bar.Delete", CategoryBar, "Delete bar", "Ctrl+Delete", "Delete the bar at the cursor."),
        new("Bar.TimeSignature", CategoryBar, "Time signature", "Ctrl+Shift+T", "Change the time signature."),
        new("Beat.MixTable", CategoryBar, "Mix table", "F10", "Change instrument, volume, pan, effects or tempo from the selected beat (mix table)."),
        new("Bar.KeySignature", CategoryBar, "Key signature", "Ctrl+K", "Change the key signature."),
        new("Bar.Clef", CategoryBar, "Clef", "K", "Change the clef of the track."),
        new("Bar.Directions", CategoryBar, "Directions", "D", "Edit repeat/DC/DS directions."),
        new("Bar.GoTo", CategoryBar, "Go to bar", "Ctrl+G", "Jump to a bar number."),
        new("Reader.ReadBar", CategoryBar, "Read current bar", "Ctrl+Alt+B", "Announce every beat of the current bar (for screen readers; also shown in the status bar)."),
        new("Reader.ReadPosition", CategoryBar, "Read position", "Ctrl+Alt+P", "Announce the track, bar, beat, string, section, time signature, tempo and time of the cursor (for screen readers; also shown in the status bar)."),
        new("Bar.First", CategoryBar, "First bar", "Ctrl+Home", "Jump to the first bar."),
        new("Bar.Last", CategoryBar, "Last bar", "Ctrl+End", "Jump to the last written beat of the last bar."),
        new("Bar.Check", CategoryBar, "Check bars", "F4", "Report bars that do not fill their time signature."),
        new("Bar.ScoreInfo", CategoryBar, "Score information", "F5", "Edit title, artist and other score information."),
        new("Section.Add", CategoryBar, "Add section", "M", "Add a new section (marker) at the cursor bar."),
        new("Section.Edit", CategoryBar, "Section editor", "Shift+Insert", "Add or edit a section marker."),
        new("Section.Previous", CategoryBar, "Previous section", "Alt+Shift+Left", "Jump to the previous section."),
        new("Section.Next", CategoryBar, "Next section", "Alt+Shift+Right", "Jump to the next section."),

        new("Note.Chord", CategoryNote, "Chord name", "A", "Attach a chord name to the beat."),
        new("Note.Text", CategoryNote, "Beat text", "T", "Attach text to the beat."),
        new("Track.Add", CategoryNote, "Add track", "Ctrl+Alt+T", "Add a new track.", "Ctrl+Shift+Insert"),
        new("Track.Delete", CategoryNote, "Delete track", "Ctrl+Shift+Delete", "Delete the selected track."),
        new("Track.Properties", CategoryNote, "Track properties", "F6", "Edit the selected track's properties."),
        new("Track.ConvertToAudio", CategoryNote, "Convert track to audio track", "", "Turn the selected instrument track into an audio track; its notation becomes a MIDI clip."),
        new("Track.Next", CategoryNote, "Next track", "Ctrl+Shift+Down", "Select the next track."),
        new("Track.Previous", CategoryNote, "Previous track", "Ctrl+Shift+Up", "Select the previous track."),

        new("View.Multitrack", CategoryView, "Show track list", "F3", "Scroll the track list (the mixer table with every track) into view; click a track's colour block there to jump to it."),
        new("View.Global", CategoryView, "Show / hide arrangement overview", "F8", "Show or hide the Arrangement (timeline) panel, the same as View > Arrangement overview."),
        new("View.Fullscreen", CategoryView, "Fullscreen", "F11", "Toggle fullscreen."),
        new("View.HorizontalScroll", CategoryView, "Horizontal score scrolling", "", "Switch the score between wrapped lines (scroll down) and one line (scroll right)."),
        new("View.PlayingBar", CategoryView, "Highlight playing bar", "", "Show or hide a translucent band over the whole bar that is playing (View > Highlight playing bar; colour and opacity in Preferences > Playback)."),
        new("View.InstrumentView",CategoryView, "Switch instrument view", "", "Cycle the instrument panel between fretboard, keyboard and drum pads (this session; the default is in Settings > Fretboard & Keyboard)."),
        new("Help.Tutorial", CategoryView, "Tutorial", "", "Open the Beginner's Guide: searchable chapters with pictures, and a PDF export (Help > Tutorial)."),
        new("Help.TutorialDetailed", CategoryView, "Detailed guide", "", "Open the Tutorial window on the Detailed Guide, the full reference to every feature (Help > Detailed guide)."),
        new("Help.CheckForUpdates", CategoryView, "Check for updates", "", "Ask GitHub whether a newer TabForge release exists (one anonymous HTTPS request)."),
        new("Transport.Record", CategoryTransport, "Record", "Ctrl+R", "Record every armed track while the song plays (press again to stop)."),
        new("Clip.Delete", CategoryClips, "Delete clip", "Delete", "Delete the selected clip."),
        new("Clip.Deselect", CategoryClips, "Deselect clip", "Escape", "Deselect the clip (Esc again clears the score selection)."),
        new("Clip.NudgeLeft", CategoryClips, "Move clip left", "Left", "Move the selected clip one beat earlier."),
        new("Clip.NudgeRight", CategoryClips, "Move clip right", "Right", "Move the selected clip one beat later."),
        new("Clip.NudgeLeftFine", CategoryClips, "Move clip left (fine)", "Shift+Left", "Move the selected clip 10 ms earlier."),
        new("Clip.NudgeRightFine", CategoryClips, "Move clip right (fine)", "Shift+Right", "Move the selected clip 10 ms later."),
        new("Clip.LaneUp", CategoryClips, "Move clip to the lane above", "Up", "Move the selected clip one lane up."),
        new("Clip.LaneDown", CategoryClips, "Move clip to the lane below", "Down", "Move the selected clip one lane down (a new lane under the last one)."),
        new("Clip.Copy", CategoryClips, "Copy clip", "Ctrl+C", "Copy the selected clip."),
    };

    private static HotkeyAction[] SliceC() => new HotkeyAction[]
    {
        new("Clip.Cut", CategoryClips, "Cut clip", "Ctrl+X", "Cut the selected clip."),
        new("Clip.Paste", CategoryClips, "Paste clip", "Ctrl+V", "Paste the copied clip at the lane position last clicked."),
        new("Clip.Duplicate", CategoryClips, "Duplicate clip", "Ctrl+D", "Duplicate the selected clip right after itself."),
        new("Clip.Mute", CategoryClips, "Mute clip", "Ctrl+M", "Mute or unmute the selected clip."),
        new("Clip.Split", CategoryClips, "Split clip at the cursor", "S", "Cut the selected clip in two at the edit cursor (the spot last clicked on the lane), or under the playhead."),
        new("Clip.Glue", CategoryClips, "Glue clips", "Ctrl+Shift+G", "Join the selected clip with the clips that continue it on its lane (same file, speed, pitch and level) into one."),
        new("Clip.FadeReset", CategoryClips, "Reset clip fades", "", "Remove the fade-in and fade-out of the selected clip."),
        new("Clip.Properties", CategoryClips, "Clip properties", "F2", "Volume, pitch, speed and name of the selected clip."),
        new("TrackRow.Copy", CategoryTrackRows, "Copy track", "Ctrl+C", "Copy the focused track (notation, clips, mixer settings, FX chain, colour and name)."),
        new("TrackRow.Cut", CategoryTrackRows, "Cut track", "Ctrl+X", "Copy the focused track and remove it from the song."),
        new("TrackRow.Paste", CategoryTrackRows, "Paste track", "Ctrl+V", "Paste the copied track after the focused track, with a unique name."),
        new("TrackRow.Duplicate", CategoryTrackRows, "Duplicate track", "Ctrl+D", "Duplicate the focused track right after itself."),
        new("TrackRow.Delete", CategoryTrackRows, "Delete track (track row)", "Delete", "Delete the focused track after a confirmation."),
        new("Range.Delete", CategoryRange, "Delete selected bars", "Delete", "Asks what to do with the selected bars (clear, remove and close the gap, insert a gap); \"Remember my answer\" makes it do that directly."),
        new("Range.Clear", CategoryRange, "Delete selected bars (leave a gap)", "", "Empty the selected bars on every track); the bar count and the clips stay."),
        new("Range.Remove", CategoryRange, "Delete selected bars (close the gap)", "Ctrl+Delete", "Remove the selected bars; later bars, sections and clips move earlier, clips inside go and clips across an edge are cut."),
        new("Range.InsertBefore", CategoryRange, "Insert a gap before the selection", "Ctrl+Shift+Space", "Insert empty bars as long as the selection in front of it; the selection and everything after move later."),
        new("Range.InsertAfter", CategoryRange, "Insert a gap after the selection", "", "Insert empty bars as long as the selection right after it."),
        new("Timeline.Snap", CategoryView, "Snap clips on / off", "Alt+S", "Turn snapping of audio and MIDI clips on or off (right-click the snap button for its settings)."),
        new("Track.Arm", CategoryTransport, "Arm track for recording", "", "Monitor the audio input through the selected track (and record it with Record)."),
        new("View.SidePanel", CategoryView, "Show / hide side panel", "", "Hide the side panel (tools, sections, practice) for more score space, or bring it back."),
        new("View.InstrumentPanel", CategoryView, "Show / hide fretboard / keyboard", "", "Hide the instrument panel (fretboard, keyboard or drum map) for more score space, or bring it back (same as View > Instrument view)."),
        new("View.BandView", CategoryView, "Show / hide Band view", "", "Switch to the Band layout (every track's instrument and tab in rows, with the arrangement below), or back to the layout you left (same as View > Band view)."),
        new("View.FretboardPosition", CategoryView, "Fretboard position: toggle top / bottom", "", "Move the fretboard / keyboard pane between above the score (default) and below it, above the timeline (same as the fretboard's right-click menu > Position)."),
        new("View.LockInstrumentSize", CategoryView, "Lock fretboard size", "", "Lock or unlock the fretboard / keyboard pane's height. Unlocked, dragging its edge resizes it and the drawing scales to fit; locked, it keeps its size."),
        new("View.LayoutCompose", CategoryView, "Layout: Compose", "Ctrl+D1", "Switch to the Compose workspace layout (score and tab editor large, fretboard and tools, small arrangement)."),
        new("View.LayoutPractice", CategoryView, "Layout: Practice", "Ctrl+D2", "Switch to the Practice workspace layout (score and fretboard large, sections panel)."),
        new("View.LayoutMix", CategoryView, "Layout: Mix", "Ctrl+D3", "Switch to the Mix workspace layout (arrangement and mixer large, small score)."),
        new("View.Mixer", CategoryView, "Mixer", "", "Open the mixer: track and group levels, pan, pitch, sound source and FX chains."),
        new("Track.FxChain", CategoryView, "Track FX chain", "", "Open the selected track's FX (plug-in) chain."),
        new("View.AutoFitTrackList", CategoryView, "Auto-resize track list to fit", "", "Turn on / off growing and shrinking the track list to fit all tracks and group rows."),
        new("View.ResetTrackRowHeight", CategoryView, "Reset track row height", "", "Put the track rows back to their default height (stretched by dragging the track list's splitter) and fit the track list to them. Double-click the splitter does the same."),
        new("Track.Wiring", CategoryView, "Plug-in wiring", "", "Open the wiring window (audio pins, MIDI input and channel filter) of the selected track's selected plug-in."),
        new("Track.MoveUp", CategoryNote, "Move track up", "Alt+Shift+Up", "Move the selected track up one place in the track list. In the Mixer window it moves the selected mixer row (a track, or a whole group) up; a track passing the top of its group joins the group above."),
        new("Track.MoveDown", CategoryNote, "Move track down", "Alt+Shift+Down", "Move the selected track down one place in the track list. In the Mixer window it moves the selected mixer row (a track, or a whole group) down; a track passing the end of its group joins the group below."),
        new("View.ShowTrackGroups", CategoryView, "Show tracks in groups", "", "Show or hide a header per mixer group (guitars, basses...) in the track list. The same setting as the Mixer's \"Groups in track list\" box and the track list's right-click menu."),
        new("Media.ManageApprovals", CategoryView, "Manage linked audio approvals", "", "Open the Linked audio window: folders on network locations or removable drives this song is waiting on, and the approvals you gave earlier (revoke them there). Also in Preferences > Files & Backups."),
        new("Mixer.MasterFx", CategoryView, "Master FX chain", "", "Open the master effects chain (applied to the whole mix after the group buses)."),
        new("Mixer.MonitorFx", CategoryView, "Mixer: Monitor FX", "", "Open the monitoring effects chain (e.g. speaker calibration). It plays after the master, live only: never included in renders or exports."),
    };

    private static HotkeyAction[] SliceD() => new HotkeyAction[]
    {
        new("Mixer.CollapseAllGroups", CategoryView, "Mixer: collapse all groups", "", "Collapse every mixer group to its group row (the track list's group boxes follow)."),
        new("Mixer.ExpandAllGroups", CategoryView, "Mixer: expand all groups", "", "Expand every mixer group to show its tracks."),
        new("Mixer.GroupRules", CategoryView, "Mixer: group rules", "", "Open the group rules editor: which instruments go in which mixer group."),
        new("Mixer.GroupFx", CategoryView, "Group bus FX chain", "", "Open the effects bus chain of the selected track's mixer group (its tracks sum into it before the master)."),
        new("Track.MidiProcessing", CategoryView, "Plug-in MIDI processing", "", "Open the MIDI processing window (filter, transpose, drum map, velocity, humanize, delay, program / CC, log) of the selected track's selected plug-in."),
        new("View.ClearScale", CategoryView, "Clear scale highlight", "", "Remove the highlighted scale from the fretboard and keyboard."),
        new("View.ScaleHighlightBrighter", CategoryView, "Scale highlight brighter", "", "Make the scale highlight on the fretboard and keyboard 10% stronger (up to 150%). The same setting as Preferences > Fretboard > Appearance > Scale highlight strength."),
        new("View.ScaleHighlightDimmer", CategoryView, "Scale highlight dimmer", "", "Make the scale highlight on the fretboard and keyboard 10% weaker (down to 10%). The same setting as Preferences > Fretboard > Appearance > Scale highlight strength."),
        new("View.ToggleAddTrackLane", CategoryView, "Show or hide the Add-track lane", "", "Show or hide the Add track strip under the last track. The same setting as Preferences > Timeline & Tracks > Show the Add-track lane."),
        new("View.ToggleTrackLines", CategoryView, "Toggle lines between tracks", "", "Show or hide the thin lines between track rows in the timeline and the track list. The same setting as Preferences > Timeline & Tracks > Show lines between tracks."),
        new("View.CyclePlayheadStyle", CategoryView, "Cycle playback position marker", "", "Switch the timeline's playback position marker between Line (default), Bar marker and Both. The same setting as Preferences > Timeline & Tracks > Playback position marker."),
        new("View.CycleStringSpacing", CategoryView, "Cycle fretboard string spacing", "", "Switch the fretboard string spacing between Compact, Natural (default) and Wide (at most 1.5x natural). The same setting as right-click the fretboard > Appearance > String spacing."),
        new("Tools.ScaleFinder", CategoryView, "Scale finder", "", "Find which scales the selected notes (or the whole song) fit, or pick any scale, and highlight it on the fretboard."),
        new("Tools.ChordFinder", CategoryView, "Chord finder", "", "Show the notes of a chord for a root and type, and insert its name on the beat under the score cursor."),
        new("Tools.SongStats", CategoryView, "Song stats", "", "Show the number of tracks, bars, notes and sections in the song."),
        new("Tools.Transpose", CategoryNote, "Transpose", "", "Transpose the notes of the selected track (or only the selected bars) by a number of semitones, in every voice. Drum tracks are skipped. One undo step."),
        new("Tools.Tuner", CategoryView, "Tuner", "", "Open the chromatic tuner: the note and cents of the sound on the armed input, with the selected track's string tunings."),
        new("View.SmoothFollow", CategoryView, "Smooth page-turn follow", "", "Switch playback follow between instant page turns and smooth (glided) page turns."),
        new("View.ZoomIn", CategoryView, "Zoom in", "Ctrl+OemPlus", "Increase the score zoom."),
        new("View.ZoomOut", CategoryView, "Zoom out", "Ctrl+OemMinus", "Decrease the score zoom."),

        // Single-key note shortcuts (classic layout). Previously hard-wired in the editor.
        new("Note.RepeatBeat", CategoryNote, "Repeat previous beat", "C", "Copy the previous beat onto the cursor."),
        new(NoteLonger, CategoryDuration, "Longer note value", "OemMinus", "Make the note value one step longer (16th to 8th to quarter...). Numpad - does the same. Preferences > Editing > \"Reverse + / - duration keys\" swaps the two default keys."),
        new(NoteShorter, CategoryDuration, "Shorter note value", "OemPlus", "Make the note value one step shorter (quarter to 8th to 16th...). Numpad + and Shift+= do the same. Preferences > Editing > \"Reverse + / - duration keys\" swaps the two default keys."),
        new("Note.PitchUp", CategoryNote, "Shift pitch up (semitone)", "Shift+Up", "Raise the selected note by a semitone."),
        new("Note.PitchDown", CategoryNote, "Shift pitch down (semitone)", "Shift+Down", "Lower the selected note by a semitone."),
        new("Note.MoveStringUp", CategoryNote, "Move note to higher string", "Alt+Up", "Move the selected note(s) to the next higher string, keeping the pitch (the fret is recalculated). Nothing changes when the pitch cannot be played there or the string is taken in that beat. On an empty spot the cursor moves to the higher string. The plain Up arrow moves only the cursor."),
        new("Note.MoveStringDown", CategoryNote, "Move note to lower string", "Alt+Down", "Move the selected note(s) to the next lower string, keeping the pitch (the fret is recalculated). Nothing changes when the pitch cannot be played there or the string is taken in that beat. On an empty spot the cursor moves to the lower string. The plain Down arrow moves only the cursor."),
        new("Note.Rest", CategoryNote, "Rest", "R", "Turn the beat into a rest (or back)."),
        new("Note.Tie", CategoryNote, "Tie note", "L", "Tie the note to the previous one."),
        new("Note.Fermata", CategoryNote, "Fermata", "F", "Hold the beat."),
        new("Note.Accent", CategoryEffects, "Accent", "Oem1", "Toggle an accent on the beat or selection (same as the Accent tool)."),
        new("Note.Staccato", CategoryEffects, "Staccato", "Shift+D1", "Play the note short."),
        new("Note.Tenuto", CategoryEffects, "Tenuto", "Shift+OemMinus", "Hold the note for its full value."),
        new("Note.Bend", CategoryEffects, "Bend", "B", "Open the bend editor (same as the Bend tool)."),
        new("Note.BendEditor", CategoryEffects, "Bend editor", "", "Open the bend editor: draw the bend curve or pick a preset."),
        new("Note.TremoloBarEditor", CategoryEffects, "Tremolo bar editor", "", "Open the tremolo bar editor: draw the whammy curve or pick a preset."),
        new("Note.TrillEditor", CategoryEffects, "Trill editor", "", "Open the trill editor: set the trill fret and speed or pick a preset."),
        new("Note.GraceEditor", CategoryEffects, "Grace note editor", "", "Open the grace note editor: fret, position, duration, dynamic and transition."),
        new("Note.HarmonicEditor", CategoryEffects, "Harmonic editor", "", "Open the harmonic editor: pick the harmonic type and its fret."),
        new("Note.HammerPull", CategoryEffects, "Hammer-on / pull-off", "H", "Legato to the next note."),
        new("Note.Vibrato", CategoryEffects, "Vibrato", "V", "Left-hand vibrato."),
        new("Note.Slide", CategoryEffects, "Legato slide", "S", "Slide into the next note."),
        new("Note.LetRing", CategoryEffects, "Let ring", "I", "Let the note ring over."),
        new("Note.Dead", CategoryEffects, "Dead note", "X", "Muted, percussive note."),
        new("Note.Ghost", CategoryEffects, "Ghost note", "O", "Very soft note in brackets."),
        new("Note.Harmonic", CategoryEffects, "Natural harmonic", "Y", "Open the harmonic editor (same as the Harmonic tool); on a note that has a harmonic, remove it."),
        new("Note.Trill", CategoryEffects, "Trill", "N", "Open the trill editor (same as the Trill tool)."),
        new("Note.TremoloBar", CategoryEffects, "Tremolo bar", "W", "Open the tremolo bar editor (same as the Tremolo bar tool)."),
        new("Note.Grace", CategoryEffects, "Grace note", "G", "Open the grace note editor (same as the Grace tool)."),
        new("Note.PalmMute", CategoryEffects, "Palm mute", "P", "Palm-muted note."),
        new("Note.FadeIn", CategoryEffects, "Fade in", "Shift+OemComma", "Volume swell in."),
        new("Note.FadeOut", CategoryEffects, "Fade out", "Shift+OemPeriod", "Volume swell out."),
        new("Note.Dot", CategoryDuration, "Dotted", "OemPeriod", "Add or remove a dot."),
        new("Note.DoubleDot", CategoryDuration, "Double dotted", "", "Make the beat double-dotted."),
        new("Note.Triplet", CategoryDuration, "Triplet", "OemQuestion", "Toggle triplet (numpad / also works)."),
        new("Bar.RepeatOpen", CategoryBar, "Repeat start", "OemOpenBrackets", "Start a repeated passage."),
        new("Bar.RepeatClose", CategoryBar, "Repeat end", "OemCloseBrackets", "End a repeated passage."),
    };
}
