<#
Regenerates docs\SBOM.md: every managed package from each project's packages.lock.json (name, version,
type, content hash) plus the native components (tfvst3.dll and the pinned Steinberg VST3 SDK it is built from).
Output is deterministic (no timestamps) so an unchanged dependency set produces an unchanged file.
Run after changing packages or rebuilding tfvst3; tools\Package-Release.ps1 runs it automatically.
#>
[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$out = Join-Path $root 'docs\SBOM.md'
$rows = New-Object System.Collections.Generic.List[string]

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Software bill of materials')
$lines.Add('')
$lines.Add('Generated by `tools/Write-Sbom.ps1` from the `packages.lock.json` files and native build records; do not edit by hand.')
$lines.Add('Restore runs in locked mode (`--locked-mode`), so these are the exact versions and hashes a build uses.')
$lines.Add('Not established by this file: vulnerability status of any component. The executables are not code-signed; release builds carry GitHub build attestations.')

# ---- managed packages ------------------------------------------------------------------------------
$locks = Get-ChildItem -Path (Join-Path $root 'src') -Filter 'packages.lock.json' -Recurse |
    Where-Object { $_.FullName -notmatch '[/\x5c](bin|obj)[/\x5c]' } | Sort-Object FullName
foreach ($lock in $locks) {
    $projectName = Split-Path (Split-Path $lock.FullName -Parent) -Leaf
    $json = [IO.File]::ReadAllText($lock.FullName) | ConvertFrom-Json
    $packages = @{}
    foreach ($tfm in $json.dependencies.PSObject.Properties) {
        foreach ($pkg in $tfm.Value.PSObject.Properties) {
            $info = $pkg.Value
            if ($info.type -eq 'Project') { continue }
            $key = "$($pkg.Name)|$($info.resolved)"
            if (-not $packages.ContainsKey($key)) {
                $packages[$key] = [pscustomobject]@{ Name = $pkg.Name; Version = $info.resolved; Type = $info.type; Hash = $info.contentHash }
            }
        }
    }
    $lines.Add('')
    $lines.Add("## Managed packages: $projectName")
    $lines.Add('')
    $lines.Add("Source: ``src/$projectName/packages.lock.json``")
    $lines.Add('')
    if ($packages.Count -eq 0) {
        $lines.Add('No NuGet package dependencies.')
    } else {
        $lines.Add('| Package | Version | Kind | Content hash (SHA-512, base64) |')
        $lines.Add('| --- | --- | --- | --- |')
        foreach ($p in ($packages.Values | Sort-Object Name, Version)) {
            $lines.Add("| $($p.Name) | $($p.Version) | $($p.Type) | ``$($p.Hash)`` |")
        }
    }
}

# ---- native components -----------------------------------------------------------------------------
$fetch = [IO.File]::ReadAllText((Join-Path $root 'native\fetch-vst3sdk.ps1'))
$sdkTag = if ($fetch -match "\`$SdkTag\s*=\s*'([^']+)'") { $Matches[1] } else { 'unknown' }
$sdkCommit = if ($fetch -match "\`$SdkCommit\s*=\s*'([0-9a-f]{40})'") { $Matches[1] } else { 'unknown' }
$submodules = New-Object System.Collections.Generic.List[string]
foreach ($m in [regex]::Matches($fetch, "'([\w\.]+)'\s*=\s*'([0-9a-f]{40})'")) { $submodules.Add("- $($m.Groups[1].Value): ``$($m.Groups[2].Value)``") }

$dll = Join-Path $root 'src\TabForge.AudioEngine\native\tfvst3.dll'
$dllHash = if (Test-Path -LiteralPath $dll) { (Get-FileHash -Algorithm SHA256 -LiteralPath $dll).Hash.ToLowerInvariant() } else { 'not present' }
$recorded = 'no native/BUILD_PROVENANCE.md yet (run native/build-tfvst3.ps1)'
$compiler = 'unknown'
$provenance = Join-Path $root 'native\BUILD_PROVENANCE.md'
if (Test-Path -LiteralPath $provenance) {
    $recorded = 'none recorded'
    foreach ($line in [IO.File]::ReadAllLines($provenance)) {
        if ($line -match '^tfvst3\.dll SHA-256:\s*`?([0-9a-fA-F]{64})`?\s*$') { $recorded = $Matches[1].ToLowerInvariant() }
        if ($line -match '^- Compiler:\s*(.+)$') { $compiler = $Matches[1].Trim() }
    }
}
$status = if ($recorded -eq $dllHash) { 'matches the recorded build' }
    elseif ($recorded -match '^[0-9a-f]{64}$') { 'DOES NOT match the recorded build' }
    else { 'has no recorded build (provenance missing)' }

$lines.Add('')
$lines.Add('## Native components')
$lines.Add('')
$lines.Add('| Component | Version / revision | Hash | Notes |')
$lines.Add('| --- | --- | --- | --- |')
$lines.Add("| tfvst3.dll (VST3 host bridge, built from ``native/tfvst3``) | built with $compiler | SHA-256 ``$dllHash`` | shipped file $status; recorded SHA-256 ``$recorded`` (see ``native/BUILD_PROVENANCE.md``) |")
$lines.Add("| Steinberg VST3 SDK (build-time only, MIT) | tag ``$sdkTag``, commit ``$sdkCommit`` | git commit id | fetched and verified by ``native/fetch-vst3sdk.ps1``; not shipped |")
$lines.Add('')
$lines.Add('VST3 SDK submodule commits (base, pluginterfaces, public.sdk):')
$lines.Add('')
foreach ($s in $submodules) { $lines.Add($s) }
$lines.Add('')
$lines.Add('Native binaries that arrive inside NuGet packages (for example AlphaSkia and SoundTouch.Net runtime assets) are covered by the package content hashes above.')

New-Item -ItemType Directory -Force (Split-Path $out -Parent) | Out-Null
[IO.File]::WriteAllText($out, (($lines -join "`r`n") + "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "SBOM -> $out ($($locks.Count) lock file(s))"
