using System.IO;
using System.Linq;
using TabForge.Models;
using TabForge.Services;
using TabForge.Views;

namespace TabForge;

// Owns: checks that the GP3-5 importer matches the reference reader on two GP5-saved files (a tie with no note before it reads
// fret 0, not the file's fret byte; a grace beat in an overfull bar keeps its note), and that Ctrl+L (tie beat) keeps a tie.
// Does not own: the importer itself (GuitarProBarConverter), the tie command (ScoreEditCommands.Marks/Ties).
// Tests: TestGp5TieGraceImport, TestTieBeatKeepsTie.
public static partial class SelfTest
{
    private const string Gp5OwnTieAfterEmptyBar = "GEZJQ0hJRVIgR1VJVEFSIFBSTyB2NS4xMBoAgMKzdgEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAGQAAAAAAAAAAAAAAAAAAAAAAADSAAAAKQEAAAoAAAAKAAAADwAAAAoAAABkAAAA/wEIAAAAByVUSVRMRSULAAAACiVTVUJUSVRMRSUJAAAACCVBUlRJU1QlCAAAAAclQUxCVU0lEQAAABBXb3JkcyBieSAlV09SRFMlEQAAABBNdXNpYyBieSAlTVVTSUMlHgAAAB1Xb3JkcyAmIE11c2ljIGJ5ICVXT1JEU01VU0lDJRYAAAAVQ29weXJpZ2h0ICVDT1BZUklHSFQlNgAAADVBbGwgUmlnaHRzIFJlc2VydmVkIC0gSW50ZXJuYXRpb25hbCBDb3B5cmlnaHQgU2VjdXJlZA0AAAAMUGFnZSAlTiUvJVAlCQAAAAhNb2RlcmF0ZXgAAAAAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAD//////////////////////////////////////////////////wAAAAACAAAAAQAAAEMEBAAAAgICAgAAAAAAAAAIB1RyYWNrIDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAQAAAADsAAAA3AAAAMgAAAC0AAAAoAAAA/////wEAAAABAAAAAgAAABgAAAAAAAAA/wAAAEMBAAAAAAAAAAAAAABkAAAAAQIDBAUGBwgJCv8D/////////////////////wAAAAABAAAAAAEAAAAAAAEAAABAAAAAAAABAAAAQAAAAAAAAAMAAAAAAEAgAggAAAAAAEAgAQ8AAAAAAEAgAQkAAAABAAAAQAAAAAAA";
    private const string Gp5OwnGraceInOverfullBar = "GEZJQ0hJRVIgR1VJVEFSIFBSTyB2NS4xMBoAgMKzdgEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAGQAAAAAAAAAAAAAAAAAAAAAAADSAAAAKQEAAAoAAAAKAAAADwAAAAoAAABkAAAA/wEIAAAAByVUSVRMRSULAAAACiVTVUJUSVRMRSUJAAAACCVBUlRJU1QlCAAAAAclQUxCVU0lEQAAABBXb3JkcyBieSAlV09SRFMlEQAAABBNdXNpYyBieSAlTVVTSUMlHgAAAB1Xb3JkcyAmIE11c2ljIGJ5ICVXT1JEU01VU0lDJRYAAAAVQ29weXJpZ2h0ICVDT1BZUklHSFQlNgAAADVBbGwgUmlnaHRzIFJlc2VydmVkIC0gSW50ZXJuYXRpb25hbCBDb3B5cmlnaHQgU2VjdXJlZA0AAAAMUGFnZSAlTiUvJVAlCQAAAAhNb2RlcmF0ZXgAAAAAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAAAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAAZAAAADQgAAAAAAAD//////////////////////////////////////////////////wAAAAABAAAAAQAAAEMEBAAAAgICAgAAAAgHVHJhY2sgMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAABAAAAAOwAAADcAAAAyAAAALQAAACgAAAD/////AQAAAAEAAAACAAAAGAAAAAAAAAD/AAAAQwEAAAAAAAAAAAAAAGQAAAABAgMEBQYHCAkK/wP/////////////////////AAAAAAEAAAAAAQAAAAAAFQAAAAD/QCkBAAAAAAAAAOg/AAACAAAA/0AgAQgAAAAA/0AgAQEAAAAA/0AgAQUAAAAA/0AgAQoAAAAA/0ApAQEAAAAAAADoPwAAAgAAAP9CIAEAACABAgAAAAD/AiABAAAAAAD/AiABAAAAAAD/AigBBQAQAAUGAAIAAAAA/wIgAQAAAAAA/wIgAQcAAAAAACAoAQUAAAgCAAAA/2IpAQgAAAAAAADoPwAAAiABAQAgAQUAAAAA/wIoAQwAAAgCAAAA/wIgAREAAAAA/wIgAQIAAAAAAAIgAQAAAAAAAAYgAQAAIAEFAAAAAAEEIAEFAAAAAAEEIAECAAAAAQAAAEAAAAAAAA==";

    private static void TestGp5TieGraceImport()
    {
        var tied = Gp5OwnImport(Gp5OwnTieAfterEmptyBar).Tracks[0].Measures[1].Cells.First(c => c.Notes.Count > 0).Notes.ToList();
        Check("gp5 own files: a tie with no note before it on its string reads fret 0, as the reference reader",
            tied.Count == 1 && tied[0].Tied && tied[0].Fret == 0 && tied[0].MidiValue == 64,
            string.Join(" ", tied.Select(n => n.Fret + "/" + n.MidiValue + (n.Tied ? "[tie]" : ""))));

        var graces = Gp5OwnImport(Gp5OwnGraceInOverfullBar).Tracks[0].Measures[0].Cells.SelectMany(c => c.Notes).Where(n => n.IsGraceNote).ToList();
        Check("gp5 own files: a grace note in an overfull bar is kept", graces.Count == 1 && graces[0].Fret == 5 && graces[0].StringIndex == 5,
            string.Join(" ", graces.Select(n => "s" + n.StringIndex + "f" + n.Fret)));
    }

    private static void TestTieBeatKeepsTie()
    {
        var w = SmNewWindow();
        try
        {
            var doc = SmOpenSong(w, SmBlankSong(4));
            var ed = SmField<TabEditorControl>(w, "Editor")!;
            ed.SelectedTrackIndex = 0;
            ed.Effects.SetDuration(4);
            ed.SetPosition(0, 0, 3); ed.Effects.EnterFret(5, autoAdvance: false);
            ed.SetPosition(0, 4, 3); ed.Effects.TieSelectedBeat();
            var beat = SmCell(doc, 0, 4);
            Check("Ctrl+L on an empty beat after a note writes the tied note", beat.Notes.Count == 1 && beat.Notes[0] is { Fret: 5, Tied: true }, beat.Notes.Count.ToString());
            ed.Effects.TieSelectedBeat();
            Check("Ctrl+L again keeps the tie (GP5 sets it, never toggles it off)", beat.Notes.Count == 1 && beat.Notes[0].Tied, beat.Notes.Count == 1 ? "tied " + beat.Notes[0].Tied : beat.Notes.Count.ToString());
        }
        finally { SmCloseWindow(w); }
    }
}